# Numba/llvmlite stack needs an older compiler for backwards compatability.
c_compiler_version:         # [linux or osx]
  - 11                      # [linux]
  - 14                      # [osx]

cxx_compiler_version:       # [linux or osx]
  - 11                      # [linux]
  - 14                      # [osx]

fortran_compiler_version:   # [linux or osx]
  - 11                      # [linux]
  - 14                      # [osx]

c_compiler:              # [win]
  - vs2022               # [win]
cxx_compiler:            # [win]
  - vs2022               # [win]

MACOSX_SDK_VERSION:    # [osx and x86_64]
  - 10.12              # [osx and x86_64]
