name: Build wheels

on:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
  workflow_dispatch:
    inputs:
      llvmdev_run_id:
        description: 'llvmdev workflow run ID (optional)'
        required: false
        type: string
      upload_wheel_to_anaconda:
        description: 'Upload wheel to Anaconda Cloud - numba channel'
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  FALLBACK_LLVMDEV_VERSION: "20"
  CONDA_CHANNEL_NUMBA: numba/label/llvm20-wheel
  ARTIFACT_RETENTION_DAYS: 7

jobs:
  load-matrix:
    runs-on: ubuntu-latest
    outputs:
      build-matrix-json: ${{ steps.load_matrix_json.outputs.build-matrix-json }}
      test-matrix-json: ${{ steps.load_matrix_json.outputs.test-matrix-json }}
    steps:
      - uses: actions/checkout@v5
      - id: load_matrix_json
        name: Load Workflow Matrix JSON
        run: |
          BUILD_MATRIX_JSON=$(jq -c .wheel_build_matrix .github/workflows/wheel_workflow_matrix.json)
          TEST_MATRIX_JSON=$(jq -c '.wheel_test_matrix | map(. + {"python_tag": ("cp" + (."python-version" | split(".") | join("")))})' .github/workflows/wheel_workflow_matrix.json)
          echo "build-matrix-json=$BUILD_MATRIX_JSON" >> $GITHUB_OUTPUT
          echo "test-matrix-json=$TEST_MATRIX_JSON" >> $GITHUB_OUTPUT

  build_wheels:
    name: build ${{ matrix.os }} (py ${{ matrix.build['python-version'] }})
    needs: load-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14, ubuntu-22.04-arm, windows-2025]
        build: ${{ fromJson(needs.load-matrix.outputs.build-matrix-json) }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          persist-credentials: false
          fetch-depth: 0

      - name: Download llvmdev Artifact
        if: ${{ inputs.llvmdev_run_id != '' }}
        uses: actions/download-artifact@v5
        with:
          name: llvmdev_for_wheel_${{ matrix.os }}
          path: llvmdev_conda_packages
          run-id: ${{ inputs.llvmdev_run_id }}
          repository: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.2.0
        with:
          auto-update-conda: true
          auto-activate-base: true

      - name: Install llvmdev
        run: |
          conda install numba/label/llvm20-wheel::llvmdev=20

      - name: Find LLVMConfig.cmake and set CMAKE_PREFIX_PATH
        run: |
          # Find LLVMConfig.cmake in the conda environment
          LLVM_CONFIG_PATH=$(find $CONDA -name "LLVMConfig.cmake" -type f | head -1)
          if [ -z "$LLVM_CONFIG_PATH" ]; then
            echo "ERROR: LLVMConfig.cmake not found in conda environment"
            find $CONDA -name "*.cmake" -type f | head -10
            exit 1
          fi
          # Extract the directory containing LLVMConfig.cmake
          LLVM_CMAKE_DIR=$(dirname "$LLVM_CONFIG_PATH")
          echo "Found LLVMConfig.cmake at: $LLVM_CONFIG_PATH"
          echo "Setting CMAKE_PREFIX_PATH to: $LLVM_CMAKE_DIR"
          echo "CMAKE_PREFIX_PATH=$LLVM_CMAKE_DIR" >> $GITHUB_ENV

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.0
        env:
          # Keep most settings in pyproject.toml; minimally wire in build+test here.
          CIBW_SKIP: "pp* *-musllinux_*"
          CIBW_PRERELEASE_PYTHONS: "1"
          CIBW_ARCHS_LINUX: "auto"
          CIBW_ARCHS_MACOS: "auto"
          CIBW_CONTAINER_ENGINE: "docker"
          CIBW_BUILD_VERBOSITY: "1"
          CIBW_BUILD: "${{ matrix.build.python_tag }}-*"

          # Windows repair: use delvewheel
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: |
            python -m pip install delvewheel
            python -m delvewheel repair --analyze-existing -w {dest_dir} {wheel}

          # For Linux containers: use mounted host conda environment
          CIBW_BEFORE_BUILD_LINUX: |
            CMAKE_PREFIX_PATH=/host/${{ env.CMAKE_PREFIX_PATH }}
            find $CMAKE_PREFIX_PATH -name "*.cmake" -type f | head -10
            export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH

          # Environment variables
          CIBW_ENVIRONMENT: |
            LLVMLITE_PACKAGE_FORMAT=wheel
            MACOSX_DEPLOYMENT_TARGET=11.0
            LDFLAGS=-v -Wl,-rpath,/usr/lib
            CMAKE_PREFIX_PATH=${{ env.CMAKE_PREFIX_PATH }}

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.build.python_tag }}
          path: ./wheelhouse/*.whl
          compression-level: 0
          if-no-files-found: error

  test_wheels:
    name: test ${{ matrix.os }} (py ${{ matrix.test.python-version }})
    needs: [load-matrix, build_wheels]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14, ubuntu-22.04-arm, windows-2025]
        test: ${{ fromJson(needs.load-matrix.outputs.test-matrix-json) }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.test['python-version'] }}
          allow-prereleases: true

      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.test.python_tag }}
          path: dist

      - name: Install and test wheel
        run: |
          PY=$(python -c 'import sys; print(sys.executable)')
          $PY -m pip install -U pip
          $PY -m pip install numpy==${{ matrix.test.numpy_test }} pytest lief
          $PY -m pip install dist/*.whl
          $PY -m llvmlite.tests

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
          compression-level: 0
          if-no-files-found: error

  upload_wheels:
    name: Upload wheels to Anaconda Cloud
    needs: [load-matrix, test_wheels]
    if: github.event_name == 'workflow_dispatch' && inputs.upload_wheel_to_anaconda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, ubuntu-22.04-arm, windows-2025]
        test: ${{ fromJson(needs.load-matrix.outputs.test-matrix-json) }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install anaconda-client
        run: python -m pip install anaconda-client

      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.test.python_tag }}
          path: wheelhouse

      - name: Upload wheels to Anaconda Cloud
        env:
          ANACONDA_API_TOKEN: ${{ secrets.NUMBA_CHANNEL_WHEEL_UPLOAD }}
        run: |
          cd wheelhouse
          for wheel in *.whl; do
            echo "Uploading $wheel"
            anaconda -t "$ANACONDA_API_TOKEN" upload --force -u numba -l dev "$wheel"
          done