name: llvmlite_osx-64_wheel_builder

on:
  pull_request:
    paths:
      - .github/workflows/llvmlite_osx-64_wheel_builder.yml
  workflow_dispatch:
    inputs:
      llvmdev_run_id:
        description: 'llvmdev workflow run ID (optional)'
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  LOCAL_LLVMDEV_ARTIFACT_PATH: ${{ github.workspace }}/llvmdev_conda_packages
  FALLBACK_LLVMDEV_VERSION: "15"
  CONDA_CHANNEL_NUMBA: numba/label/osx_wheel
  VALIDATION_PYTHON_VERSION: "3.12"
  ARTIFACT_RETENTION_DAYS: 7

jobs:
  osx-64-build:
    name: osx-64-build
    runs-on: macos-13
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: false

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          conda-remove-defaults: true
          auto-update-conda: true
          auto-activate-base: true

      - name: Download llvmdev Artifact
        if: ${{ inputs.llvmdev_run_id != '' }}
        uses: actions/download-artifact@v4
        with:
          name: llvmdev_osx-64
          path: llvmdev_conda_packages
          run-id: ${{ inputs.llvmdev_run_id }}
          repository: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install build dependencies
        run: |
          set -x
          if [ "${{ inputs.llvmdev_run_id }}" != "" ]; then
              CHAN="file:///${{ env.LOCAL_LLVMDEV_ARTIFACT_PATH }}"
          else
              CHAN="${{ env.CONDA_CHANNEL_NUMBA }}"
          fi
          # Install delocate along with other dependencies
          conda install -c "$CHAN" llvmdev=${{ env.FALLBACK_LLVMDEV_VERSION }} cmake libxml2 python-build
          conda install -c conda-forge delocate # Install delocate

      - name: Build wheel
        run: python -m build

      - name: Repair wheel with delocate
        run: |
          set -x
          # Create a directory for the repaired wheels
          mkdir dist_repaired

          # Get the most recent wheel
          whl=$(ls -t dist/*.whl | head -n 1)
          echo "Processing wheel: $whl"

          # Debug: List contents of Conda lib directory and set DYLD_LIBRARY_PATH
          echo "=== Listing $CONDA_PREFIX/lib ==="
          ls -l $CONDA_PREFIX/lib
          echo "=== Exporting DYLD_LIBRARY_PATH ==="
          export DYLD_LIBRARY_PATH=$CONDA_PREFIX/lib:$DYLD_LIBRARY_PATH
          echo "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH"

          # Run delocate, telling it where to find conda libs and where to output
          # Use -v for verbose output, -d to show dependencies
          # Add --dylibs-path .dylibs to explicitly set the target lib folder within the wheel
          delocate-wheel -v -d --dylibs-path .dylibs -L $CONDA_PREFIX/lib -w dist_repaired "$whl"

          echo "=== Repaired wheel filename ==="
          ls -la dist_repaired/*.whl

      - name: Upload llvmlite wheel
        uses: actions/upload-artifact@v4
        with:
          name: llvmlite-osx-64-py${{ matrix.python-version }}
          # Upload the repaired wheel from the new directory
          path: dist_repaired/*.whl
          compression-level: 0
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
          if-no-files-found: error

  osx-64-validate:
    name: osx-64-validate
    needs: osx-64-build
    runs-on: macos-13
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ env.VALIDATION_PYTHON_VERSION }}
          conda-remove-defaults: true
          auto-update-conda: true
          auto-activate-base: true

      - name: Install validation dependencies
        run: conda install -c defaults wheel twine keyring rfc3986

      - name: Download llvmlite wheels
        uses: actions/download-artifact@v4
        with:
          name: llvmlite-osx-64-py${{ matrix.python-version }}
          path: dist

      - name: Validate wheels
        run: |
          set -e  # Exit on any error
          cd dist
          
          for WHL_FILE in *.whl; do
            echo "=== Validating $WHL_FILE ==="
            
            # Check wheel structure
            twine check "$WHL_FILE"
            
            # Check dylib paths
            wheel unpack "$WHL_FILE"
            WHEEL_DIR=$(echo "$WHL_FILE" | cut -d "-" -f1 -f2)
            DYLIB=$(find "$WHEEL_DIR" -iname "libllvmlite.dylib")
            
            if [ -z "$DYLIB" ]; then
              echo "Error: libllvmlite.dylib not found in $WHL_FILE"
              exit 1
            fi
            
            echo "=== Checking dynamic library dependencies ==="
            otool -L "$DYLIB"
            
            # Verify library paths
            LIBS=("libz.1.dylib" "libc++.1.dylib")
            for LIB in "${LIBS[@]}"; do
              if ! otool -L "$DYLIB" | grep -q "/usr/lib/$LIB"; then
                echo "Error: $LIB path is incorrect in $WHL_FILE"
                exit 1
              fi
            done
          done

  osx-64-test:
    name: osx-64-test
    needs: osx-64-validate
    runs-on: macos-13
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: false

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download llvmlite wheel
        uses: actions/download-artifact@v4
        with:
          name: llvmlite-osx-64-py${{ matrix.python-version }}
          path: dist

      - name: Install and test
        run: |
          # Debug pip information first
          echo "=== Initial Pip Information ==="
          python3 -m pip debug --verbose

          # Try to install with verbose output
          echo "=== Attempting pip install with verbose output ==="
          python3 -m pip install -v dist/*.whl
          
          # Basic import test
          python3 -c "import llvmlite.binding as llvm; print(f'LLVM version: {llvm.get_version()}')"
          # Run full test suite
          python3 -m llvmlite.tests