name: llvmdev-build

on:
  workflow_dispatch:

jobs:
  linux-64:
    name: Build LLVMDEV (linux-64)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH

      - name: Setup Conda Environment
        run: |
          source $HOME/miniconda/bin/activate
          conda create -n builder conda-build -y

      - name: Build
        run: |
          source $HOME/miniconda/bin/activate
          conda activate builder
          RECIPE_NAME=./conda-recipes/llvmdev
          conda build $RECIPE_NAME
          echo "OUTPUT=$(conda build --output $RECIPE_NAME)" >> $GITHUB_ENV

      - name: Upload LLVMDEV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvmdev-linux-x86_64
          path: ${{ env.OUTPUT }}
          retention-days: 7
          if-no-files-found: error 

  win-64:
    name: Build LLVMDEV (win-64)
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Install Miniconda
        shell: pwsh
        run: |
          $wc = New-Object net.webclient
          $wc.Downloadfile("https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe", "Miniconda3-latest-Windows-x86_64.exe")
          Start-Process "Miniconda3-latest-Windows-x86_64.exe" "/S /D=C:\Miniconda3" -Wait

      - name: Setup Conda Environment
        shell: cmd
        run: |
          call C:\Miniconda3\Scripts\activate.bat
          conda create -n builder conda-build -y

      - name: Build
        shell: cmd
        run: |
          call C:\Miniconda3\Scripts\activate.bat
          conda activate builder
          set "RECIPE_NAME=.\conda-recipes\llvmdev"
          conda build %RECIPE_NAME%
          for /f "tokens=* USEBACKQ" %%F in (`conda build --output %RECIPE_NAME%`) do set OUTPUT=%%F
          echo OUTPUT=%OUTPUT% >> %GITHUB_ENV%

      - name: Upload LLVMDEV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvmdev-windows-x86_64
          path: ${{ env.OUTPUT }}
          retention-days: 7
          if-no-files-found: error

